### ISSUE TITLE
Keep some form of navigation on category pages

### ISSUE THREAD

**Issue by iambrianfung** [brave/store-brave-com#28] opened 2023-03-21 21:12 UTC
### Describe the problem

I am always frustrated when I navigate to a category page but cannot switch categories without going all the way back to the home page. Going to "All Products" does not suffice.

### Describe the proposed solution

Keep `section.hero` or `div.flex-wrap` from home page on each of the category and product pages.
Alternatively, have a menu bar to be able to switch between categories easily.

### Importance

Nice to have

### Additional Information

<img width="1542" alt="Screenshot 2023-03-21 at 17 11 53" src="https://user-images.githubusercontent.com/24831890/226741971-58ba4872-3419-4e18-9170-d6b6c0fb0668.png">

**Comment by AlanBreck** [comment] 2023-03-21 21:18
Is this a dupe of https://github.com/brave/store-brave-com/issues/12?

**Comment by AlanBreck** [comment] 2023-03-21 21:22
#12 is actually probably closer to how we'll implement, so maybe keep that one? Ultimately, completely up to you. :-)

**Comment by AlanBreck** [comment] 2023-03-21 21:34
Yeah, I think so. Maybe just mention in that issue that the filter/navigation should exist on all list pages.

**Closed** 2023-03-21 22:00 UTC
Labels: feature-request
